server:
  port: 8085

spring:
  profiles:
    active: dev, local
  application:
    name: exam-system
  cloud:
    nacos:
      discovery:
        username: ${EXAM_NACOS_USERNAME}
        password: ${EXAM_NACOS_PASSWORD}
  datasource:
    username: ${EXAM_DB_USERNAME}
    password: ${EXAM_DB_PASSWORD}

exam:
  resource:
    local-storage-root: ${EXAM_RESOURCE_STORAGE_ROOT:./tmp_resource}
  jwt:
    secret: "mySuperSecretKeyThatIsAtLeast32BytesLongForHS512"
    access-token-expiration: 1800000
    refresh-token-expiration: 604800000
  api-test:
    enabled: false
