server:
  port: 8089

spring:
  profiles:
    active: dev, local
  application:
    name: exam-resource
  cloud:
    nacos:
      discovery:
        username: ${EXAM_NACOS_USERNAME:nacos}
        password: ${EXAM_NACOS_PASSWORD:nacos}

exam:
  resource:
    local-storage-root: ${EXAM_RESOURCE_STORAGE_ROOT:./tmp_resource}
  jwt:
    secret: "mySuperSecretKeyThatIsAtLeast32BytesLongForHS512"
    access-token-expiration: 1800000
    refresh-token-expiration: 604800000
  api-test:
    enabled: false
