package com.maghert.examcommon.exception;

import com.maghert.examcommon.web.ApiResponseCode;
import lombok.Getter;

@Getter
public enum DomainErrorCode {

    AUTHENTICATION_REQUIRED(1001, ApiResponseCode.UNAUTHORIZED, "未登录或登录态失效"),
    TOKEN_INVALID(1002, ApiResponseCode.UNAUTHORIZED, "登录凭证无效"),
    ROLE_CONTEXT_REQUIRED(1003, ApiResponseCode.UNAUTHORIZED, "缺少角色上下文"),
    REQUEST_CONTEXT_INVALID(1004, ApiResponseCode.UNAUTHORIZED, "请求头上下文无效"),
    DATE_TIME_FORMAT_INVALID(1005, ApiResponseCode.BAD_REQUEST, "时间格式必须为 yyyy-MM-dd HH:mm:ss"),
    QUESTION_TYPE_UNSUPPORTED(1006, ApiResponseCode.BAD_REQUEST, "不支持的题型"),
    QUESTION_AUDIT_STATUS_UNSUPPORTED(1007, ApiResponseCode.BAD_REQUEST, "不支持的审核状态"),
    CLASS_NOT_FOUND(1101, ApiResponseCode.NOT_FOUND, "班级不存在"),
    CLASS_CODE_INVALID(1102, ApiResponseCode.BAD_REQUEST, "班级码无效"),
    TEACHER_CLASS_LIMIT_EXCEEDED(1103, ApiResponseCode.CONFLICT, "建班数量超限"),
    STUDENT_CLASS_LIMIT_EXCEEDED(1104, ApiResponseCode.CONFLICT, "入班数量超限"),
    STUDENT_ALREADY_IN_CLASS(1105, ApiResponseCode.CONFLICT, "已在班级中"),
    PENDING_CLASS_APPLICATION_CONFLICT(1106, ApiResponseCode.CONFLICT, "存在待审批入班申请"),
    MANDATORY_CLASS_QUIT_FORBIDDEN(1107, ApiResponseCode.FORBIDDEN, "强制班级不可退班"),
    TEACHER_CLASS_FORBIDDEN(1108, ApiResponseCode.FORBIDDEN, "教师无权操作非本人班级"),
    CLASS_DELETE_STILL_HAS_STUDENTS(1109, ApiResponseCode.CONFLICT, "删除前仍有学生在班级中"),
    CLASS_APPROVAL_STATUS_CONFLICT(1110, ApiResponseCode.CONFLICT, "审批状态冲突"),
    CLASS_MEMBER_NOT_FOUND(1111, ApiResponseCode.NOT_FOUND, "班级成员不存在"),
    CLASS_IMPORT_FILE_REQUIRED(1112, ApiResponseCode.BAD_REQUEST, "导入文件不能为空"),
    CLASS_IMPORT_READ_FAILED(1113, ApiResponseCode.INTERNAL_SERVER_ERROR, "导入文件读取失败"),
    CLASS_TEACHER_ID_INVALID(1114, ApiResponseCode.BAD_REQUEST, "teacherId 无效"),
    CLASS_EXPORT_FORBIDDEN(1115, ApiResponseCode.FORBIDDEN, "无导出权限"),
    CLASS_APPROVAL_TARGET_REQUIRED(1116, ApiResponseCode.BAD_REQUEST, "审批对象不能为空"),
    ROLE_NOT_FOUND(1201, ApiResponseCode.NOT_FOUND, "角色不存在"),
    PERMISSION_NOT_FOUND(1202, ApiResponseCode.NOT_FOUND, "权限不存在"),
    PERMISSION_ASSIGNMENT_FORBIDDEN(1203, ApiResponseCode.FORBIDDEN, "权限分配越权"),
    CONFIG_NOT_FOUND(1204, ApiResponseCode.NOT_FOUND, "配置不存在"),
    CONFIG_UPDATE_SECOND_FACTOR_REQUIRED(1205, ApiResponseCode.FORBIDDEN, "配置修改需二次验证"),
    LOG_EXPORT_APPROVAL_REQUIRED(1206, ApiResponseCode.FORBIDDEN, "日志导出需审批"),
    BACKUP_FAILED(1207, ApiResponseCode.INTERNAL_SERVER_ERROR, "备份失败"),
    RESTORE_FAILED(1208, ApiResponseCode.INTERNAL_SERVER_ERROR, "恢复失败"),
    SYSTEM_STATUS_CONFLICT(1209, ApiResponseCode.CONFLICT, "状态冲突"),
    TEMPORARY_AUTHORIZATION_EXPIRED(1210, ApiResponseCode.FORBIDDEN, "临时授权失效"),
    SECOND_FACTOR_VALIDATION_FAILED(1211, ApiResponseCode.FORBIDDEN, "二次验证失败"),
    SYSTEM_PERMISSION_QUERY_FORBIDDEN(1212, ApiResponseCode.FORBIDDEN, "无权限读取权限清单"),
    SYSTEM_OPERATION_FORBIDDEN(1213, ApiResponseCode.FORBIDDEN, "无操作权限"),
    SYSTEM_LOG_EXPORT_FORBIDDEN(1214, ApiResponseCode.FORBIDDEN, "无导出权限"),
    SYSTEM_BACKUP_FORBIDDEN(1215, ApiResponseCode.FORBIDDEN, "仅系统运维可执行备份"),
    SUPER_ADMIN_REQUIRED(1216, ApiResponseCode.FORBIDDEN, "仅超级管理员可操作"),
    BACKUP_RECORD_NOT_FOUND(1217, ApiResponseCode.NOT_FOUND, "备份记录不存在"),
    SYSTEM_BACKUP_QUERY_FORBIDDEN(1218, ApiResponseCode.FORBIDDEN, "无权限查询备份记录"),
    SYSTEM_BACKUP_TYPE_INVALID(1219, ApiResponseCode.BAD_REQUEST, "备份类型不合法"),
    QUESTION_CATEGORY_NOT_FOUND(1301, ApiResponseCode.NOT_FOUND, "题库分类不存在"),
    QUESTION_NOT_FOUND(1302, ApiResponseCode.NOT_FOUND, "题目不存在"),
    QUESTION_AUDIT_STATUS_CONFLICT(1303, ApiResponseCode.CONFLICT, "题目审核状态冲突"),
    QUESTION_REFERENCE_UPDATE_FORBIDDEN(1304, ApiResponseCode.CONFLICT, "被引用题目不可修改关键字段"),
    QUESTION_IMPORT_LIMIT_EXCEEDED(1305, ApiResponseCode.BAD_REQUEST, "单次导入题目数量超限"),
    QUESTION_CATEGORY_SCOPE_FORBIDDEN(1306, ApiResponseCode.FORBIDDEN, "题库分类访问越权"),
    QUESTION_DIFFICULTY_INVALID(1307, ApiResponseCode.BAD_REQUEST, "题目难度必须在 1 到 5 之间"),
    QUESTION_ANSWER_REQUIRED(1308, ApiResponseCode.BAD_REQUEST, "答案不能为空"),
    QUESTION_OPTIONS_REQUIRED(1309, ApiResponseCode.BAD_REQUEST, "客观题选项不能为空"),
    QUESTION_CATEGORY_SCOPE_CONFLICT(1310, ApiResponseCode.CONFLICT, "题库分类作用域不可变更"),
    QUESTION_IMPORT_FILE_REQUIRED(1311, ApiResponseCode.BAD_REQUEST, "导入文件不能为空"),
    QUESTION_IMPORT_READ_FAILED(1312, ApiResponseCode.INTERNAL_SERVER_ERROR, "导入文件读取失败"),
    QUESTION_REJECT_REASON_REQUIRED(1313, ApiResponseCode.BAD_REQUEST, "驳回原因不能为空"),
    QUESTION_CATEGORY_PARENT_INVALID(1314, ApiResponseCode.BAD_REQUEST, "题库分类父节点无效"),
    QUESTION_MANAGE_FORBIDDEN(1315, ApiResponseCode.FORBIDDEN, "无权限管理题目"),
    QUESTION_QUERY_FORBIDDEN(1316, ApiResponseCode.FORBIDDEN, "无权限查询题目"),
    QUESTION_AUDIT_FORBIDDEN(1317, ApiResponseCode.FORBIDDEN, "仅管理员可审核题目"),
    QUESTION_ACCESS_FORBIDDEN(1318, ApiResponseCode.FORBIDDEN, "无权限操作该题目"),
    QUESTION_CATEGORY_MANAGE_FORBIDDEN(1319, ApiResponseCode.FORBIDDEN, "无权限管理题库分类"),
    QUESTION_CATEGORY_ID_REQUIRED(1320, ApiResponseCode.BAD_REQUEST, "categoryId is required"),
    QUESTION_CATEGORY_DISABLED(1321, ApiResponseCode.CONFLICT, "题库分类已禁用"),
    PAPER_NOT_FOUND(1401, ApiResponseCode.NOT_FOUND, "试卷不存在"),
    PAPER_MANAGE_FORBIDDEN(1402, ApiResponseCode.FORBIDDEN, "无权限管理试卷"),
    PAPER_STATUS_CONFLICT(1403, ApiResponseCode.CONFLICT, "试卷状态冲突"),
    PAPER_QUESTION_ACCESS_FORBIDDEN(1404, ApiResponseCode.FORBIDDEN, "题目不在当前组卷授权范围内"),
    PAPER_AUTO_ASSEMBLE_FAILED(1405, ApiResponseCode.CONFLICT, "自动组卷失败，题目池无法满足当前比例约束"),
    PAPER_REJECT_REASON_REQUIRED(1406, ApiResponseCode.BAD_REQUEST, "驳回试卷时必须填写原因"),
    PAPER_CLASS_ACCESS_FORBIDDEN(1407, ApiResponseCode.FORBIDDEN, "无权将试卷发布到该班级"),
    PAPER_QUESTION_REQUIRED(1408, ApiResponseCode.BAD_REQUEST, "试卷至少需要一道题目"),
    PAPER_PASS_SCORE_INVALID(1409, ApiResponseCode.BAD_REQUEST, "及格分必须大于 0 且不超过总分"),
    PAPER_EXAM_TIME_INVALID(1410, ApiResponseCode.BAD_REQUEST, "考试时长必须大于 0"),
    PAPER_RATIO_INVALID(1411, ApiResponseCode.BAD_REQUEST, "组卷比例参数不合法"),
    PAPER_PUBLISH_CLASS_REQUIRED(1412, ApiResponseCode.BAD_REQUEST, "发布试卷时必须指定班级"),
    PAPER_RECYCLE_TIME_CONFLICT(1413, ApiResponseCode.CONFLICT, "试卷尚未到可回收时间"),
    PAPER_AUDIT_RESULT_INVALID(1414, ApiResponseCode.BAD_REQUEST, "试卷审核结果不合法"),
    PAPER_SCHEDULED_TIME_REQUIRED(1415, ApiResponseCode.BAD_REQUEST, "发布时间必须符合 yyyy-MM-dd HH:mm:ss"),
    PAPER_CLASS_STATUS_INVALID(1416, ApiResponseCode.CONFLICT, "班级状态不允许发布试卷"),
    PAPER_EXPORT_FORBIDDEN(1417, ApiResponseCode.FORBIDDEN, "无权限导出试卷"),
    PAPER_EXPORT_APPROVAL_REQUIRED(1418, ApiResponseCode.FORBIDDEN, "试卷导出需审批"),
    EXAM_NOT_FOUND(1501, ApiResponseCode.NOT_FOUND, "考试不存在"),
    EXAM_MANAGE_FORBIDDEN(1502, ApiResponseCode.FORBIDDEN, "无权限管理考试"),
    EXAM_STATUS_CONFLICT(1503, ApiResponseCode.CONFLICT, "考试状态冲突"),
    EXAM_PAPER_STATUS_INVALID(1504, ApiResponseCode.CONFLICT, "试卷状态不允许创建考试"),
    EXAM_CLASS_ACCESS_FORBIDDEN(1505, ApiResponseCode.FORBIDDEN, "无权将考试创建到该班级"),
    EXAM_CLASS_REQUIRED(1506, ApiResponseCode.BAD_REQUEST, "创建考试时必须指定班级"),
    EXAM_START_TIME_REQUIRED(1507, ApiResponseCode.BAD_REQUEST, "开考时间必须符合 yyyy-MM-dd HH:mm:ss"),
    EXAM_DURATION_INVALID(1508, ApiResponseCode.BAD_REQUEST, "考试时长必须大于 0"),
    EXAM_PAPER_CLASS_SCOPE_CONFLICT(1509, ApiResponseCode.CONFLICT, "考试班级不在试卷已发布范围内"),
    EXAM_UPDATE_PARAM_REQUIRED(1510, ApiResponseCode.BAD_REQUEST, "至少提供一个可更新字段"),
    EXAM_START_TIME_UPDATE_FORBIDDEN(1511, ApiResponseCode.CONFLICT, "开考后不可修改开考时间"),
    EXAM_DURATION_EXTENSION_REQUIRED(1512, ApiResponseCode.CONFLICT, "开考后仅允许延长考试时长"),
    EXAM_DISTRIBUTE_TARGET_REQUIRED(1513, ApiResponseCode.BAD_REQUEST, "分发考试时必须指定学生"),
    EXAM_DISTRIBUTE_STATUS_CONFLICT(1514, ApiResponseCode.CONFLICT, "当前考试状态不允许分发"),
    EXAM_STUDENT_SCOPE_CONFLICT(1515, ApiResponseCode.CONFLICT, "存在不在考试班级范围内的学生"),
    EXAM_STUDENT_STATUS_CONFLICT(1516, ApiResponseCode.CONFLICT, "存在未通过入班审批的学生"),
    EXAM_TOGGLE_REASON_REQUIRED(1517, ApiResponseCode.BAD_REQUEST, "暂停或恢复考试时必须填写原因"),
    EXAM_RETEST_APPLY_NOT_FOUND(1518, ApiResponseCode.NOT_FOUND, "补考申请不存在"),
    EXAM_RETEST_STATUS_CONFLICT(1519, ApiResponseCode.CONFLICT, "补考申请状态冲突"),
    EXAM_RETEST_RESULT_INVALID(1520, ApiResponseCode.BAD_REQUEST, "补考审核结果不合法"),
    EXAM_RETEST_REASON_REQUIRED(1521, ApiResponseCode.BAD_REQUEST, "驳回补考申请时必须填写原因"),
    EXAM_DISTRIBUTE_SCORE_CONFLICT(1522, ApiResponseCode.CONFLICT, "考试成绩已开始处理，不允许重新分发"),
    EXAM_SUBMIT_FORBIDDEN(1523, ApiResponseCode.FORBIDDEN, "无权限提交答卷"),
    EXAM_SUBMIT_STATUS_CONFLICT(1524, ApiResponseCode.CONFLICT, "当前考试状态不允许提交答卷"),
    EXAM_SUBMIT_QUESTION_CONFLICT(1525, ApiResponseCode.CONFLICT, "提交答案与当前考试题目不匹配"),
    EXAM_RETEST_APPLY_FORBIDDEN(1526, ApiResponseCode.FORBIDDEN, "无权限发起补考申请"),
    SCORE_NOT_FOUND(1601, ApiResponseCode.NOT_FOUND, "成绩不存在"),
    SCORE_QUERY_FORBIDDEN(1602, ApiResponseCode.FORBIDDEN, "无权限查询成绩"),
    SCORE_DETAIL_FORBIDDEN(1603, ApiResponseCode.FORBIDDEN, "无权限查看成绩明细"),
    SCORE_PUBLISH_FORBIDDEN(1604, ApiResponseCode.FORBIDDEN, "无权限发布成绩"),
    SCORE_PUBLISH_TARGET_REQUIRED(1605, ApiResponseCode.BAD_REQUEST, "发布成绩时必须指定考试和班级"),
    SCORE_PUBLISH_STATUS_CONFLICT(1606, ApiResponseCode.CONFLICT, "存在未完成评分的成绩记录，当前不可发布"),
    SCORE_MANUAL_FORBIDDEN(1607, ApiResponseCode.FORBIDDEN, "无权限批阅成绩"),
    SCORE_MANUAL_SCORE_INVALID(1608, ApiResponseCode.BAD_REQUEST, "批阅分数不合法"),
    SCORE_DETAIL_NOT_FOUND(1609, ApiResponseCode.NOT_FOUND, "成绩明细不存在"),
    SCORE_MANUAL_STATUS_CONFLICT(1610, ApiResponseCode.CONFLICT, "当前成绩状态不允许继续批阅"),
    SCORE_MANUAL_QUESTION_TYPE_CONFLICT(1611, ApiResponseCode.CONFLICT, "当前题目不是主观题，不能人工批阅"),
    SCORE_AUTO_FORBIDDEN(1612, ApiResponseCode.FORBIDDEN, "无权限执行自动评分"),
    SCORE_AUTO_STATUS_CONFLICT(1613, ApiResponseCode.CONFLICT, "当前成绩状态不允许自动评分"),
    SCORE_ANALYZE_FORBIDDEN(1614, ApiResponseCode.FORBIDDEN, "无权限进行成绩分析"),
    SCORE_ANALYZE_DIMENSION_INVALID(1615, ApiResponseCode.BAD_REQUEST, "成绩分析维度不合法"),
    SCORE_RECHECK_FORBIDDEN(1616, ApiResponseCode.FORBIDDEN, "无权限发起成绩复核"),
    SCORE_RECHECK_STATUS_CONFLICT(1617, ApiResponseCode.CONFLICT, "当前成绩状态不允许发起复核"),
    SCORE_APPEAL_NOT_FOUND(1618, ApiResponseCode.NOT_FOUND, "成绩申诉不存在"),
    SCORE_APPEAL_HANDLE_FORBIDDEN(1619, ApiResponseCode.FORBIDDEN, "无权限处理成绩申诉"),
    SCORE_APPEAL_HANDLE_STATUS_CONFLICT(1620, ApiResponseCode.CONFLICT, "当前成绩申诉状态不允许处理"),
    SCORE_APPEAL_RESULT_INVALID(1621, ApiResponseCode.BAD_REQUEST, "成绩申诉处理结果不合法"),
    SCORE_EXPORT_FORBIDDEN(1622, ApiResponseCode.FORBIDDEN, "无权限导出成绩"),
    SCORE_UPDATE_FORBIDDEN(1623, ApiResponseCode.FORBIDDEN, "无权限修改成绩"),
    SCORE_UPDATE_APPROVER_INVALID(1624, ApiResponseCode.BAD_REQUEST, "审批人信息不合法"),
    SCORE_UPDATE_SCORE_INVALID(1625, ApiResponseCode.BAD_REQUEST, "修改后的成绩不合法"),
    SCORE_UPDATE_STATUS_CONFLICT(1626, ApiResponseCode.CONFLICT, "当前成绩状态不允许修改"),
    ISSUE_NOT_FOUND(1801, ApiResponseCode.NOT_FOUND, "问题不存在"),
    ISSUE_TYPE_INVALID(1802, ApiResponseCode.BAD_REQUEST, "问题类型不合法"),
    ISSUE_STATUS_INVALID(1803, ApiResponseCode.CONFLICT, "当前问题状态不允许执行该操作"),
    ISSUE_HANDLE_FORBIDDEN(1804, ApiResponseCode.FORBIDDEN, "无权限处理该问题"),
    ISSUE_TRANSFER_FORBIDDEN(1805, ApiResponseCode.FORBIDDEN, "无权限转派该问题"),
    ISSUE_CLOSE_FORBIDDEN(1806, ApiResponseCode.FORBIDDEN, "无权限关闭该问题"),
    ISSUE_QUERY_FORBIDDEN(1807, ApiResponseCode.FORBIDDEN, "无权限查看该问题"),
    ISSUE_TRACK_FORBIDDEN(1808, ApiResponseCode.FORBIDDEN, "无权限跟踪该问题"),
    ISSUE_CONFIRM_RESULT_INVALID(1809, ApiResponseCode.BAD_REQUEST, "问题关闭确认结果不合法"),
    ISSUE_TRANSFER_TARGET_INVALID(1810, ApiResponseCode.BAD_REQUEST, "转派目标不合法"),
    ISSUE_EXAM_SCOPE_REQUIRED(1811, ApiResponseCode.BAD_REQUEST, "考试类问题至少关联一个 examId 或 classId"),
    REALTIME_SESSION_FORBIDDEN(1901, ApiResponseCode.FORBIDDEN, "无权限进入当前考试会话"),
    REALTIME_PROGRESS_FORBIDDEN(1902, ApiResponseCode.FORBIDDEN, "无权限保存当前考试进度"),
    REALTIME_SOCKET_FORBIDDEN(1903, ApiResponseCode.FORBIDDEN, "无权限建立当前考试实时连接"),
    REALTIME_REPORT_SCREEN_FORBIDDEN(1904, ApiResponseCode.FORBIDDEN, "无权限上报切屏事件"),
    REALTIME_SUBMIT_CONFLICT(1905, ApiResponseCode.CONFLICT, "当前考试状态不允许提交"),
    REALTIME_DOWNSTREAM_ERROR(1906, ApiResponseCode.INTERNAL_SERVER_ERROR, "下游考试核心服务调用失败"),
    RESOURCE_NOT_FOUND(1701, ApiResponseCode.NOT_FOUND, "资源不存在"),
    RESOURCE_ACCESS_FORBIDDEN(1702, ApiResponseCode.FORBIDDEN, "无权限访问资源"),
    RESOURCE_KEY_INVALID(1703, ApiResponseCode.BAD_REQUEST, "资源标识不合法"),
    RESOURCE_TEMPLATE_TYPE_INVALID(1704, ApiResponseCode.BAD_REQUEST, "模板类型不合法");

    private final int code;
    private final ApiResponseCode responseCode;
    private final String defaultMessage;

    DomainErrorCode(int code, ApiResponseCode responseCode, String defaultMessage) {
        this.code = code;
        this.responseCode = responseCode;
        this.defaultMessage = defaultMessage;
    }
}
